---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
labels:
  org.opencontainers.image.title: RitiBackup
  org.opencontainers.image.description: Encrypted Home Assistant backups to WebDAV
  org.opencontainers.image.source: https://github.com/sahelea1/ha-riti-webdav-backup
  org.opencontainers.image.licenses: MIT
